version: '3.8'

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: strings_db
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"

  web:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - db
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/strings"]
      interval: 30s
      timeout: 10s
      retries: 3

  test:
    build: .
    command: pytest tests.py
    depends_on:
      - db
